on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > deploy_key
          chmod 600 deploy_key

          ssh -i deploy_key -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user/WasteManagement_Backend  # Update this path
            git pull origin main
            source /home/ec2-user/WasteManagement_Backend/venv/bin/activate  # If using a virtual environment
            pip install -r Requirements.txt  # Update dependencies if needed
            
            # Kill old uvicorn process if running
            pkill -f "uvicorn main:app" || true
            
            # Restart FastAPI in the background
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &
          EOF
